-- O admin cria itens novos no navegador com um id temporário (Date.now())
-- antes de existir linha no banco. Pra isso funcionar com upsert, a coluna
-- id precisa aceitar valor explícito no insert — "generated by default"
-- ainda auto-gera quando nenhum id é passado, mas permite informar um.
alter table public.bags  alter column id set generated by default;
alter table public.looks alter column id set generated by default;
